<?php
/**
 * @file
 * Code for the Perun project feature.
 */

include_once('perun_project.features.inc');

/**
 * Implementation of hook_install()
 */
function perun_project_install() {
  // add link to projects list in Perun shortcust for editors
  $shortcut_set = shortcut_set_load('shortcut-set-perun-editor');
  $link = array(
    'link_path' => 'admin/content/projects',
    'link_title' => t('Projects'),
    'weight' => -30,
  );
  $shortcut_set->links[] = $link;
  shortcut_set_save($shortcut_set);
}

/**
 * Implementation of hook_uninstall()
 */
function perun_project_uninstall() {
// todo
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function perun_project_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'node/add' on 'admin/content' page.
  if ($root_path == 'admin/content/projects') { 
    $item = menu_get_item('node/add/project');
    
    // change the title of the link
    $item['title'] = "Add a new project";
    
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter()
 */
function perun_project_form_news_node_form_alter(&$form, &$form_state, $form_id){
  // titles for creating nodes are hard to translate to Slovenian language, so we customize them
  drupal_set_title(t("Create a new project"));
}