<?php
/**
 * @file
 * Code for the Perun page feature.
 */

include_once('perun_page.features.inc');

/**
 * Implementation of hook_install()
 */
function perun_page_install() {
  // add link to projects list in Perun shortcust for editors  
  $shortcut_set = shortcut_set_load('shortcut-set-perun-editor');
  $link = array(
    'link_path' => 'admin/content',
    'link_title' => t('Pages'),
    'weight' => -50,
  );
  $shortcut_set->links[] = $link;
  shortcut_set_save($shortcut_set);
}

/**
 * Implementation of hook_uninstall()
 */
function perun_page_uninstall() {
// todo
}

/**
 * Implementation of hook_menu()
 */
function perun_page_menu() {
  $items['admin/content/node'] = array(
    'access callback' => FALSE,
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function perun_page_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'node/add' on 'admin/content' page.
  if ($root_path == 'admin/content') {
    // remove node/add link
    unset($data['actions']['output'][0]);
    
    $item = menu_get_item('node/add/page');    
    // change the title of the link
    $item['title'] = "Add a new page";
    
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter()
 */
function perun_page_form_page_node_form_alter(&$form, &$form_state, $form_id){
  // titles for creating nodes are hard to translate to Slovenian language, so we customize them
  drupal_set_title(t("Create a new page"));
}